# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-18 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=datetime.date(2018, 5, 18))),
                ('config_file', models.FileField(upload_to=b'')),
            ],
        ),
    ]
