# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-18 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
