# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-18 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180518_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='name',
            field=models.CharField(default='caleb', max_length=64),
            preserve_default=False,
        ),
    ]
