# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-19 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dashboard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='config_file',
            field=models.FilePathField(path=b'C:\\Users\\nakamura9a\\Documents\\code\\pet_projects\\plantlink_scada\\media'),
        ),
    ]
